fix: fixes incomplete type for player api function
adamgrieger/spotify-web-api-ts pull request #23
Opened 2021-02-08 06:32 UTC by patrick-motard

`getCurrentlyPlayingTrack` returns an empty string if no song is currently
playing. The type response of that function is incorrect, leading to
complile errors. This PR fixes the issue by correcting the type
response.

Fixes #22

2021-02-10 05:24 UTC, adamgrieger requested changes
I need to create a contribution guide of some sort, but can you remove the `package-lock.json` file? I used `yarn` while developing this, so there's already a `yarn`-specific lock file. I don't know if people generally commit two different types of lock files.

2021-02-10 05:24 UTC, adamgrieger commented on src/apis/PlayerApi.ts
> +  ): Promise<CurrentlyPlaying | String> {
The string type should be `string` instead of `String`. The [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/basic-types.html#about-number-string-boolean-symbol-and-object) has a note about this.

2021-02-10 07:34 UTC, patrick-motard commented on src/apis/PlayerApi.ts
> +  ): Promise<CurrentlyPlaying | String> {
Oops! Fixed in https://github.com/adamgrieger/spotify-web-api-ts/pull/23/commits/59c13e4e4044e64d1ebfd72c9dbcb805f8b195b7

2021-02-10 07:35 UTC, patrick-motard commented
> I need to create a contribution guide of some sort, but can you remove the `package-lock.json` file? I used `yarn` while developing this, so there's already a `yarn`-specific lock file. I don't know if people generally commit two different types of lock files.

I've removed the `package-lock.json` in https://github.com/adamgrieger/spotify-web-api-ts/pull/23/commits/59c13e4e4044e64d1ebfd72c9dbcb805f8b195b7. I've also added it to `.gitignore` so that npm users don't include it in future PRs. 🥳

2021-02-11 06:47 UTC, adamgrieger approved these changes

2021-02-11 06:47 UTC, merged

2021-02-11 06:48 UTC, adamgrieger commented
Thanks, @patrick-motard!

2021-02-11 06:50 UTC, adamgrieger commented
:tada: This PR is included in version 1.4.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/spotify-web-api-ts/v/1.4.5)
- [GitHub release](https://github.com/adamgrieger/spotify-web-api-ts/releases/tag/v1.4.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: